
import type { Metadata } from "next";

import "./globals.css";
import Header from "./layouts/header/Header";
import Footer from "./layouts/footer/Footer";
import AppProviders from "@components/global/provider/AppProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
        <Header/>
      {children}
      <Footer/>
        </AppProviders>

      </body>
    </html>
  );
}
